# Generated by Django 2.0.5 on 2018-06-06 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180606_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='perfrom_time',
            new_name='perform_time',
        ),
    ]
