# Generated by Django 2.0.5 on 2018-06-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180606_1233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receivers',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='base_transaction_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paycom_time_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
