# Generated by Django 2.0.5 on 2018-06-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180606_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='cancel_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='paycom_time_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='perform_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
