# Generated by Django 2.0.5 on 2018-06-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180606_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reason',
            field=models.SmallIntegerField(default=None, null=True),
        ),
    ]
