# Generated by Django 2.0.5 on 2018-06-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180607_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
