# Generated by Django 2.0.5 on 2018-06-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_basicauth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicAuth',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='create_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
