# Generated by Django 2.0.5 on 2018-06-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180618_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=250)),
            ],
        ),
    ]
